In [1]:
import jax
import jax.numpy as jp

def take(x: jp.ndarray, index: int):
    return x[index]

x = jp.arange(25).reshape((5, 5))

In [2]:
jax.vmap(take, in_axes=(None, 0), out_axes=1)(x, jp.array([2,1,0]))

Array([[10,  5,  0],
       [11,  6,  1],
       [12,  7,  2],
       [13,  8,  3],
       [14,  9,  4]], dtype=int32)

In [8]:
x = jp.arange(125).reshape(5, 5, 5)
ids = jp.array([[0, 1], [2,3]])

In [ ]:
def unfold(x: jp.ndarray, dim: int, p: int):
    n = x.shape[dim]
    ids = jp.arange(p)[:p * n // p].reshape(-1, p)
    

In [12]:
x[ids].transpose(0, 2, 3, 1)

Array([[[[ 0, 25],
         [ 1, 26],
         [ 2, 27],
         [ 3, 28],
         [ 4, 29]],

        [[ 5, 30],
         [ 6, 31],
         [ 7, 32],
         [ 8, 33],
         [ 9, 34]],

        [[10, 35],
         [11, 36],
         [12, 37],
         [13, 38],
         [14, 39]],

        [[15, 40],
         [16, 41],
         [17, 42],
         [18, 43],
         [19, 44]],

        [[20, 45],
         [21, 46],
         [22, 47],
         [23, 48],
         [24, 49]]],


       [[[50, 75],
         [51, 76],
         [52, 77],
         [53, 78],
         [54, 79]],

        [[55, 80],
         [56, 81],
         [57, 82],
         [58, 83],
         [59, 84]],

        [[60, 85],
         [61, 86],
         [62, 87],
         [63, 88],
         [64, 89]],

        [[65, 90],
         [66, 91],
         [67, 92],
         [68, 93],
         [69, 94]],

        [[70, 95],
         [71, 96],
         [72, 97],
         [73, 98],
         [74, 99]]]], dtype=int32)

In [18]:
jp.take(x, ids, axis=1).transpose(0, 1, 3, 2)

Array([[[[  0,   5],
         [  1,   6],
         [  2,   7],
         [  3,   8],
         [  4,   9]],

        [[ 10,  15],
         [ 11,  16],
         [ 12,  17],
         [ 13,  18],
         [ 14,  19]]],


       [[[ 25,  30],
         [ 26,  31],
         [ 27,  32],
         [ 28,  33],
         [ 29,  34]],

        [[ 35,  40],
         [ 36,  41],
         [ 37,  42],
         [ 38,  43],
         [ 39,  44]]],


       [[[ 50,  55],
         [ 51,  56],
         [ 52,  57],
         [ 53,  58],
         [ 54,  59]],

        [[ 60,  65],
         [ 61,  66],
         [ 62,  67],
         [ 63,  68],
         [ 64,  69]]],


       [[[ 75,  80],
         [ 76,  81],
         [ 77,  82],
         [ 78,  83],
         [ 79,  84]],

        [[ 85,  90],
         [ 86,  91],
         [ 87,  92],
         [ 88,  93],
         [ 89,  94]]],


       [[[100, 105],
         [101, 106],
         [102, 107],
         [103, 108],
         [104, 109]],

        [[110, 115],
        

In [20]:
jp.take(x, ids, axis=2)

Array([[[[  0,   1],
         [  2,   3]],

        [[  5,   6],
         [  7,   8]],

        [[ 10,  11],
         [ 12,  13]],

        [[ 15,  16],
         [ 17,  18]],

        [[ 20,  21],
         [ 22,  23]]],


       [[[ 25,  26],
         [ 27,  28]],

        [[ 30,  31],
         [ 32,  33]],

        [[ 35,  36],
         [ 37,  38]],

        [[ 40,  41],
         [ 42,  43]],

        [[ 45,  46],
         [ 47,  48]]],


       [[[ 50,  51],
         [ 52,  53]],

        [[ 55,  56],
         [ 57,  58]],

        [[ 60,  61],
         [ 62,  63]],

        [[ 65,  66],
         [ 67,  68]],

        [[ 70,  71],
         [ 72,  73]]],


       [[[ 75,  76],
         [ 77,  78]],

        [[ 80,  81],
         [ 82,  83]],

        [[ 85,  86],
         [ 87,  88]],

        [[ 90,  91],
         [ 92,  93]],

        [[ 95,  96],
         [ 97,  98]]],


       [[[100, 101],
         [102, 103]],

        [[105, 106],
         [107, 108]],

        [[110, 111],
   